/* @nice-view-image-tool {"version":1,"sprites":[{"name":"open","sel":[0,0,12,12],"out":[12,12]},{"name":"offline","sel":[13,0,12,12],"out":[12,12]},{"name":"offline_selected","sel":[26,0,12,12],"out":[12,12]},{"name":"online","sel":[39,0,12,12],"out":[12,12]},{"name":"online_selected","sel":[52,0,12,12],"out":[12,12]}]} */

/*
 * Auto-generated by nice!view Image Tool
 * 5 sprite(s)
 */

#include <lvgl.h>

/* ── open  12×12  src(0,0) ── */
#ifndef LV_ATTRIBUTE_IMG_OPEN
#define LV_ATTRIBUTE_IMG_OPEN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_OPEN uint8_t
    open_map[] = {
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xf0
};

const lv_img_dsc_t open = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 12,
    .header.h = 12,
    .data_size = 32,
    .data = open_map,
};

/* ── offline  12×12  src(13,0) ── */
#ifndef LV_ATTRIBUTE_IMG_OFFLINE
#define LV_ATTRIBUTE_IMG_OFFLINE
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_OFFLINE uint8_t
    offline_map[] = {
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        0xd9, 0xb0, 0x80, 0x10, 0x00, 0x00, 0x80, 0x10, 0x80, 0x10, 0x00, 0x00, 0x00, 0x00, 0x80,
        0x10, 0x80, 0x10, 0x00, 0x00, 0x80, 0x10, 0xd9, 0xb0
};

const lv_img_dsc_t offline = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 12,
    .header.h = 12,
    .data_size = 32,
    .data = offline_map,
};

/* ── offline_selected  12×12  src(26,0) ── */
#ifndef LV_ATTRIBUTE_IMG_OFFLINE_SELECTED
#define LV_ATTRIBUTE_IMG_OFFLINE_SELECTED
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_OFFLINE_SELECTED uint8_t
    offline_selected_map[] = {
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        0xd9, 0xb0, 0x80, 0x10, 0x3f, 0xc0, 0xbf, 0xd0, 0xbf, 0xd0, 0x3f, 0xc0, 0x3f, 0xc0, 0xbf,
        0xd0, 0xbf, 0xd0, 0x3f, 0xc0, 0x80, 0x10, 0xd9, 0xb0
};

const lv_img_dsc_t offline_selected = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 12,
    .header.h = 12,
    .data_size = 32,
    .data = offline_selected_map,
};

/* ── online  12×12  src(39,0) ── */
#ifndef LV_ATTRIBUTE_IMG_ONLINE
#define LV_ATTRIBUTE_IMG_ONLINE
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_ONLINE uint8_t
    online_map[] = {
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        0xff, 0xf0, 0x80, 0x10, 0x80, 0x10, 0x80, 0x10, 0x80, 0x10, 0x80, 0x10, 0x80, 0x10, 0x80,
        0x10, 0x80, 0x10, 0x80, 0x10, 0x80, 0x10, 0xff, 0xf0
};

const lv_img_dsc_t online = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 12,
    .header.h = 12,
    .data_size = 32,
    .data = online_map,
};

/* ── online_selected  12×12  src(52,0) ── */
#ifndef LV_ATTRIBUTE_IMG_ONLINE_SELECTED
#define LV_ATTRIBUTE_IMG_ONLINE_SELECTED
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_ONLINE_SELECTED uint8_t
    online_selected_map[] = {
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        0xff, 0xf0, 0x80, 0x10, 0xbf, 0xd0, 0xbf, 0xd0, 0xbf, 0xd0, 0xbf, 0xd0, 0xbf, 0xd0, 0xbf,
        0xd0, 0xbf, 0xd0, 0xbf, 0xd0, 0x80, 0x10, 0xff, 0xf0
};

const lv_img_dsc_t online_selected = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 12,
    .header.h = 12,
    .data_size = 32,
    .data = online_selected_map,
};